[theme]
primaryColor = "#FF0000"              # Vermelho La Moda
backgroundColor = "#0E1117"           # Fundo escuro
secondaryBackgroundColor = "#1A1C1E"  # Sidebar
textColor = "#FFFFFF"
font = "sans serif"
